# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r-cLu6d_1qOyrYebqbgJyF-gdF3N3a8e
"""

# Simpan skrip ini dengan nama app.py

import streamlit as st

# Judul aplikasi
st.title("Contoh Dashboard Streamlit di Google Colab")

# Tambahkan teks ke dalam aplikasi
st.write("Selamat datang di dashboard Streamlit di Google Colab!")